steps:
- command:
  - "make ci_test"
  label: ":llama: Tests"
  agents:
  - "queue=default"
- command:
  - "make ci_build"
  label: ":golang: Build"
  agents:
  - "queue=default"
- command:
  - "make ci_lint"
  label: ":llama: Linting"
  agents:
  - "queue=default"
